version: "3"

services:
    anki-container:
        image: jameshi16/anki-docker-sync-server
        container_name: anki-container

        restart: always
        ports:
          - "8080:8080"
        volumes:
          - data:/opt/anki
          - ./ssl:/opt/https
        env_file: .env

volumes:
    data:
